### ISSUE TITLE
docker network name

### ISSUE THREAD

**Issue by honoref** [myth/ansible-traefik-docker#1]
Does the name of the docker network in the task "Create traefik docker network" is right ? (file tasks/configre.yml)
Perhaps better if it use the variable traefik_docker_network, like below ?

```yml
- name: Create traefik docker network
  docker_network:
    name: "{{ traefik_docker_network }}"
    state: present
```
